on:
  push:
    branches: [python]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  python:
    runs-on: codeberg-tiny-lazy
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv run --only-dev poe --executor simple format:python --check
      - run: uv run --only-dev poe --executor simple lint:python
